## Python 102

**Scenario:** Today we are going to build upon the for loops of yesterday. Who has ever got to the cash register at costco, or whole foods, seen the total and asked "how did I spend that much?". Today we have a grocery list of items and prices, but we do not have infinite money (unfortunately), so we need to have a program that will look at our grocery list and help us manage our shopping and cost.

### Learning goals:

Today we will:
 - revisit what for loop does, using a dictionary
 - use `break` to adjust loop activity
 - use nested loops to navigate a nested dictionary
 - write a robust function that will take any nested dictionary of items, costs, and print out your shopping list, stopping when the total cost gets to high, and telling you the average cost per item in your cart.

Let's revisit what a for loop does. Here we have a list of items, and a separate list of costs. We are going to write a loop to print each item, it's cost, and the total of our grocery list.

In [42]:
items = ['cheese', 'whole milk', 'kefir', 'tofu four-pack', 'kale', 'oranges', 'ham', '''ben & jerry's''']
cost = [2.79, 3.42, 4.50, 12.00, 2.75, 3.64, 25.00, 5.29]
print(items)
print(cost)

['cheese', 'whole milk', 'kefir', 'tofu four-pack', 'kale', 'oranges', 'ham', "ben & jerry's"]
[2.79, 3.42, 4.5, 12.0, 2.75, 3.64, 25.0, 5.29]


In [6]:
for i in items:
    print('I need to buy '+i)

I need to buy cheese
I need to buy whole milk
I need to buy kefir
I need to buy tofu four-pack
I need to buy kale
I need to buy oranges
I need to buy ham
I need to buy ben & jerry's


In [9]:
for i in items:
    print(f'I need to buy {i}')

I need to buy cheese
I need to buy whole milk
I need to buy kefir
I need to buy tofu four-pack
I need to buy kale
I need to buy oranges
I need to buy ham
I need to buy ben & jerry's


In [10]:
for i in items:
    print("- []",i)

- [] cheese
- [] whole milk
- [] kefir
- [] tofu four-pack
- [] kale
- [] oranges
- [] ham
- [] ben & jerry's


In [11]:
list(zip(items,cost))

[('cheese', 2.79),
 ('whole milk', 3.42),
 ('kefir', 4.5),
 ('tofu four-pack', 12.0),
 ('kale', 2.75),
 ('oranges', 3.64),
 ('ham', 25.0),
 ("ben & jerry's", 5.29)]

In [14]:
grocery_dict = dict(zip(items,cost))
grocery_dict.get('cheese')

2.79

In [15]:
grocery_dict.keys()

dict_keys(['cheese', 'whole milk', 'kefir', 'tofu four-pack', 'kale', 'oranges', 'ham', "ben & jerry's"])

In [16]:
grocery_dict.values()

dict_values([2.79, 3.42, 4.5, 12.0, 2.75, 3.64, 25.0, 5.29])

In [17]:
grocery_dict.popitem()

("ben & jerry's", 5.29)

In [18]:
grocery_dict.pop('cheese')

2.79

In [19]:
grocery_dict

{'whole milk': 3.42,
 'kefir': 4.5,
 'tofu four-pack': 12.0,
 'kale': 2.75,
 'oranges': 3.64,
 'ham': 25.0}

In [21]:
grocery_dict['cheese']=2.79

```
items = ['cheese', 'whole milk', 'kefir', 'tofu four-pack', 'kale', 'oranges', 'ham', 'ben & jerry's']
cost = [2.79, 3.42, 4.50, 12.00, 2.75, 3.64, 25.00, 5.29]
```

![groc-cart](https://images.pexels.com/photos/1389103/pexels-photo-1389103.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260)

### For loops:
First, let's create a for-loop that prints each item in the list with "I need to buy: " item.

Let's make that a little nicer looking:

```
print("I need to buy: ")
for item in items:
   print(" - [ ] ", item)
```

Okay, we want to work through a dictionary, so what's one way to convert those two lists to a dictionary?

_Hint_: Check [this](https://www.w3schools.com/python/ref_func_zip.asp) documentation. 

So let's now add the total grocery bill at the end:

In [28]:
total=0
for key, val in grocery_dict.items():
    total += val
    print(f"{key} costs ${val}")
print ("Total is $"+ str(total))

whole milk costs $3.42
kefir costs $4.5
tofu four-pack costs $12.0
kale costs $2.75
oranges costs $3.64
ham costs $25.0
cheese costs $2.79
Total is $54.1


Does this look reasonable?

What if you only had $25? 

How can you build it out to stop adding items when the total is over $25?

### While, break, and continue
What does a while loop look like in Python?

In [29]:
i = 1
while i < 6:
  print(i)
  i += 1

1
2
3
4
5


In [30]:
name = "Andy"
while name:
    print(name)
    name = name[:-1]

Andy
And
An
A


In [35]:
a = 'b'
a[:-1]

''

In [36]:
#Falsey things
''
[]
{}
()
False
0
None

False

In [37]:
id("")

4391480432

In [38]:
id(False)

4389896592

In [39]:
""==False

False

In [40]:
while cost:
    print(cost.pop())

5.29
25.0
3.64
2.75
12.0
4.5
3.42
2.79


In [41]:
cost

[]

- What is break and continue?
- Are they different? How?
- Run the following code:

In [45]:
i = 0
while i < 6:
  i += 1
  if i == 3:
    print("foo")
    continue
  print(i)

1
2
foo
4
5
6


How does the code above work?

Now run this code:

In [46]:
i = 0
while i < 6:
  i += 1
  if i == 3:
    print("foo")
    break
  print(i)

1
2
foo


Why is the output different?

It stopped at foo, why?

We can also include `breaks` in for-loops.

What would we use to **stop** the for loop if the total reached $25?

In [49]:
total=0
for key, val in grocery_dict.items():
    print(f"{key} costs ${val}")
    if total + val > 25:
        break
    total += val
print ("Total is $"+ str(total))

whole milk costs $3.42
kefir costs $4.5
tofu four-pack costs $12.0
kale costs $2.75
oranges costs $3.64
Total is $22.67


In [50]:
total=0
for key, val in grocery_dict.items():
    print(f"{key} costs ${val}")
    if total + val < 25:
        continue
    total += val
print ("Total is $"+ str(total))

whole milk costs $3.42
kefir costs $4.5
tofu four-pack costs $12.0
kale costs $2.75
oranges costs $3.64
ham costs $25.0
cheese costs $2.79
Total is $27.79


What if we wanted to use continue and break to stop the program if an item costs more than **$10** ?

### Nested Loops

In [3]:
list2 = [1,2,3,4,5]

for x in list2:
  print('loop1:', x)
  for y in list2:
    print('loop2---', y)

loop1: 1
loop2--- 1
loop2--- 2
loop2--- 3
loop2--- 4
loop2--- 5
loop1: 2
loop2--- 1
loop2--- 2
loop2--- 3
loop2--- 4
loop2--- 5
loop1: 3
loop2--- 1
loop2--- 2
loop2--- 3
loop2--- 4
loop2--- 5
loop1: 4
loop2--- 1
loop2--- 2
loop2--- 3
loop2--- 4
loop2--- 5
loop1: 5
loop2--- 1
loop2--- 2
loop2--- 3
loop2--- 4
loop2--- 5


What do you expect to see? Why?

Here's a more complicated example, what is it doing?

In [52]:
list2 = [1,2,3,4,5]
list3= ['a','b','c','d','e']
for x in list2:
  print('loop1:', x)
  for y in list3:
    print('loop2---', y)

loop1: 1
loop2--- a
loop2--- b
loop2--- c
loop2--- d
loop2--- e
loop1: 2
loop2--- a
loop2--- b
loop2--- c
loop2--- d
loop2--- e
loop1: 3
loop2--- a
loop2--- b
loop2--- c
loop2--- d
loop2--- e
loop1: 4
loop2--- a
loop2--- b
loop2--- c
loop2--- d
loop2--- e
loop1: 5
loop2--- a
loop2--- b
loop2--- c
loop2--- d
loop2--- e


In [54]:
i = 2
while(i < 100):
   j = 2
   while(j <= (i/j)):
      if not(i%j): break
      j = j + 1
   if (j > i/j) : print( i, " is prime")
   i = i + 1

print ("Good bye!")

2  is prime
3  is prime
5  is prime
7  is prime
11  is prime
13  is prime
17  is prime
19  is prime
23  is prime
29  is prime
31  is prime
37  is prime
41  is prime
43  is prime
47  is prime
53  is prime
59  is prime
61  is prime
67  is prime
71  is prime
73  is prime
79  is prime
83  is prime
89  is prime
97  is prime
Good bye!


In [80]:
for i in range(2,10):
   print(f"i: {i}")
   j = 2
   while(j <= (i/j)):
      print(f"j: {j}")
      if not(i%j): break
      j = j + 1
   if (j > i/j) : print( i, " is prime")
   i = i + 1

print ("Good bye!")

i: 2
2  is prime
i: 3
3  is prime
i: 4
j: 2
i: 5
j: 2
5  is prime
i: 6
j: 2
i: 7
j: 2
7  is prime
i: 8
j: 2
i: 9
j: 2
j: 3
Good bye!


Here is a more robust shopping list of nested dictionaries:
```
shopping_dict = {'Grocieries': {'ben & jerrys': 5.29, 'cheese': 2.79,'ham': 25.0, 'kale': 2.75,'kefir': 4.5,'oranges': 3.64,'tofu four-pack': 12.0,'whole milk': 3.42},
                 'House supplies': {'toilet paper pack': 16.50, 'clorox spray': 6.43, 'kleenex': 2.50,},
                 'Pet supplies': {'Taste of the Wild': 65.20, 'squeaky toy': 4.50, 'duck feet': 8.45}}
```

write the nested for loops to print out each grocery list with its total

_Hint_

- use [this link](https://pyformat.info/#number) for help in formatting the total to two decimal places

In [56]:
shopping_dict = {'Grocieries': {'ben & jerrys': 5.29, 'cheese': 2.79,'ham': 25.0, 'kale': 2.75,'kefir': 4.5,'oranges': 3.64,'tofu four-pack': 12.0,'whole milk': 3.42},
                 'House supplies': {'toilet paper pack': 16.50, 'clorox spray': 6.43, 'kleenex': 2.50,},
                 'Pet supplies': {'Taste of the Wild': 65.20, 'squeaky toy': 4.50, 'duck feet': 8.45}}


In [59]:
shopping_dict.keys()

dict_keys(['Grocieries', 'House supplies', 'Pet supplies'])

In [ ]:
running_total = 0
for cat, cat_dict in shopping_dict.items():
        

In [72]:
running_total = 0
for category, cat_list in shopping_dict.items():
    for cat_item, cat_value in cat_list.items():
        running_total += cat_value
        print(f"{category} item {cat_item} costs ${cat_value}. Total cost: ${running_total}")

Grocieries item ben & jerrys costs $5.29. Total cost: $5.29
Grocieries item cheese costs $2.79. Total cost: $8.08
Grocieries item ham costs $25.0. Total cost: $33.08
Grocieries item kale costs $2.75. Total cost: $35.83
Grocieries item kefir costs $4.5. Total cost: $40.33
Grocieries item oranges costs $3.64. Total cost: $43.97
Grocieries item tofu four-pack costs $12.0. Total cost: $55.97
Grocieries item whole milk costs $3.42. Total cost: $59.39
House supplies item toilet paper pack costs $16.5. Total cost: $75.89
House supplies item clorox spray costs $6.43. Total cost: $82.32
House supplies item kleenex costs $2.5. Total cost: $84.82
Pet supplies item Taste of the Wild costs $65.2. Total cost: $150.01999999999998
Pet supplies item squeaky toy costs $4.5. Total cost: $154.51999999999998
Pet supplies item duck feet costs $8.45. Total cost: $162.96999999999997


In [76]:
running_total = 0
for category, cat_list in shopping_dict.items():
    for cat_item, cat_value in cat_list.items():
        running_total += cat_value
        print(f"{category} item {cat_item} costs ${cat_value}")
    print(f"Total cost of {category} is {running_total}".title())

Grocieries item ben & jerrys costs $5.29
Grocieries item cheese costs $2.79
Grocieries item ham costs $25.0
Grocieries item kale costs $2.75
Grocieries item kefir costs $4.5
Grocieries item oranges costs $3.64
Grocieries item tofu four-pack costs $12.0
Grocieries item whole milk costs $3.42
Total Cost Of Grocieries Is 59.39
House supplies item toilet paper pack costs $16.5
House supplies item clorox spray costs $6.43
House supplies item kleenex costs $2.5
Total Cost Of House Supplies Is 84.82
Pet supplies item Taste of the Wild costs $65.2
Pet supplies item squeaky toy costs $4.5
Pet supplies item duck feet costs $8.45
Total Cost Of Pet Supplies Is 162.96999999999997


In [28]:
total=0
for key, val in grocery_dict.items():
    total += val
    print(f"{key} costs ${val}")
print ("Total is $"+ str(total))

whole milk costs $3.42
kefir costs $4.5
tofu four-pack costs $12.0
kale costs $2.75
oranges costs $3.64
ham costs $25.0
cheese costs $2.79
Total is $54.1


In [49]:
total=0
for key, val in grocery_dict.items():
    print(f"{key} costs ${val}")
    if total + val > 25:
        break
    total += val
print ("Total is $"+ str(total))

whole milk costs $3.42
kefir costs $4.5
tofu four-pack costs $12.0
kale costs $2.75
oranges costs $3.64
Total is $22.67


### Functions

**Built-in functions** <br>
Many useful functions are already built into Python:<br>

`print()`: print the given string or variable's value<br>
`type()`: returns the datatype of the argument<br>
`len()`: returns the length of an array<br>
`sum()`: returns the sum of the array's values<br>
`min()`: returns the smallest member of an array <br>
`max()`: returns the largest member of an array<br>


**Writing your own functions**

```
def sayHello():
  print("Hello!")
```
How do we run it?

```
sayHello()
```

Let's talk about arguments or parameters. Let's say we want to make this function more dynamic and print out whatever we want! How would we do that?
```
def shout(phrase):
  print(phrase + "!!!")
shout("oh hai")
```

What if we don't pass in an argument? What happens?
Maybe we can establish a default value for the argument in case it isn't passed in.

```
def shout(phrase = "oh hai"):
  print(phrase + "!!!")

shout()
shout("bye")
```

What if we wanted to run a function, take its output and put it in to another function?

```
def add_one(number):
  return number + 1

def times_five(number):
  return number * 5

number_plus_one = add_one(1)
answer = times_five(number_plus_one)
print(answer)
```

What will the above code return?

Adapt your shopping list nested for-loop to be wrapped in a function you could call on any shopping list of nested dictionaries.

### Mathematical Notation and Measures of Central Tendency 

median vs mode vs mean<br>
What's the difference?


`samp_list = [1,1,1,1,2,2,2,3,3,10,44]`

How could you write a for loop to calculate the mean?

In [ ]:
samp_list = [1,1,1,1,2,2,2,3,3,10,44]




### Integration

adapt your function to do the following:
- stop the nested loop if a grocery total goes over $30
- print out the average cost of per item in your cart

## Jupyter Bonus

This doesn't really fit in with the rest of Python 102, but Jupyter is incredibly flexible! Here are two examples of embedding beautiful LaTex scripting in a notebook.

In [1]:
%%latex # this will make the entire cell LaTeX syntax
$$\lim\limits_{x \to \infty} \exp(-x) = 0$$

<IPython.core.display.Latex object>

In [2]:
from IPython.display import Math
# this imports a function called Math() in which you can pass in a raw string of LaTeX
Math('F(k) = \int_{-\infty}^{\infty} f(x) e^{2\pi i k} dx')

<IPython.core.display.Math object>